version: '{build}'

environment:
  VERSION: 1.1.0
  TARGET_CONFIGURATION: Release

image: Visual Studio 2022
platform: Any CPU

branches:
  only:
    - master

only_commits:
  message: /(build|publish)/
#  files:
#    - src/*

before_build:
- cmd: >-
    dotnet --version

    dotnet restore

build_script:
- cmd: >-
    dotnet pack .\src\LinqAsync -c %TARGET_CONFIGURATION% -p:VersionPrefix=%VERSION%

    dotnet pack .\src\LinqAsync.EFCore -c %TARGET_CONFIGURATION% -p:VersionPrefix=%VERSION%

artifacts:
  - path: "src/**/*.nupkg"
    name: "LinqAsync NuGet Packages"

deploy:
  - provider: NuGet
    api_key:
      secure: UIRvzyHvZdb41Gixu5+IJ9nrOhfuj7Ey9mU52bL/kJAUFBLZN+tPQR2eydBnEDAp
    artifact: /.*\.nupkg/
